cp ../../../smack-omemo/smack-tcp/build/libs/smack-tcp-4.2.1-SNAPSHOT.jar .
cp ../../../smack-omemo/smack-repl/build/libs/smack-repl-4.2.1-SNAPSHOT.jar .
cp ../../../smack-omemo/smack-bosh/build/libs/smack-bosh-4.2.1-SNAPSHOT.jar .
cp ../../../smack-omemo/smack-sasl-provided/build/libs/smack-sasl-provided-4.2.1-SNAPSHOT.jar .
cp ../../../smack-omemo/smack-compression-jzlib/build/libs/smack-compression-jzlib-4.2.1-SNAPSHOT.jar .
cp ../../../smack-omemo/smack-legacy/build/libs/smack-legacy-4.2.1-SNAPSHOT.jar .
cp ../../../smack-omemo/smack-im/build/libs/smack-im-4.2.1-SNAPSHOT.jar .
cp ../../../smack-omemo/smack-extensions/build/libs/smack-extensions-4.2.1-SNAPSHOT.jar .
cp ../../../smack-omemo/smack-resolver-minidns/build/libs/smack-resolver-minidns-4.2.1-SNAPSHOT.jar .
cp ../../../smack-omemo/smack-core/build/libs/smack-core-4.2.1-SNAPSHOT.jar .
cp ../../../smack-omemo/smack-experimental/build/libs/smack-experimental-4.2.1-SNAPSHOT.jar .
cp ../../../smack-omemo/smack-omemo/build/libs/smack-omemo-4.2.1-SNAPSHOT.jar .
cp ../../../smack-omemo/smack-omemo-signal/build/libs/smack-omemo-signal-4.2.1-SNAPSHOT.jar .
cp ../../../smack-omemo/smack-android-extensions/build/libs/smack-android-extensions-4.2.1-SNAPSHOT.jar . 
cp ../../../smack-omemo/smack-android/build/libs/smack-android-4.2.1-SNAPSHOT.jar .
